name: Echo Current Date

on:
  push:        # Runs on every push
    branches:
      - '**'   # All branches

jobs:
  echo-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print current date
        run: |
          echo "Current date (UTC): $(date -u)"

      - name: Print current date (local)
        run: |
          echo "Current date (local): $(date)"

  workflow_dispatch: # Manual trigger from Actions UI